model_name: Pangu
# patch embedding
patch_shape: [2, 2, 2]
constant_mask_paths: null
# earth layer
depths: [2, 6]
# earth block
max_drop_path: 0.2
# earth attn 3d
heads: [6, 12]
dim: 192
dropout_rate: 0
window_size: [2, 4, 4]