model_name: Pangu
# patch embedding
patch_size: [1, 2, 2]
smoothing_kernel_size: 5
segmented_smooth_boundary_width: null
# earth layer
depths: [2, 2, 6]
# earth block
max_drop_path_ratio: 0.3
# earth attn 3d
heads: [8, 8, 16]
embed_dim: 256
dropout_rate: 0
window_size: [3, 7, 7]