model_name: Pangu
# patch embedding
patch_size: [1, 2, 2]
smoothing_kernel_size: 5
segmented_smooth_boundary_width: 10
const_mask_paths: null
# earth layer
depths: [2, 6]
# earth block
max_drop_path_ratio: 0.2
# earth attn 3d
heads: [6, 12]
embed_dim: 192
dropout_rate: 0
window_size: [3, 4, 4]