# For more default settings and their description, please refer to:
# `../site-package/hydra/conf/__init__.py`
hydra:
  run:  
    dir: outputs/${now:%Y-%m-%d}/${now:%H:%M:%S} # where to save the logs
  job:
    chdir: False # whether to move to log folder
  output_subdir: .hydra # .hydra log dir name
  job_logging:
    root:
      level: DEBUG # 1st filter
    handlers:
      console:
        level: INFO # 2nd filter
      file:
        level: DEBUG # 2nd filter
  # verbose: [src.managers.data_manager] 

defaults:
  - data: rwrf_dense
  - lightning: pangu_rwrf
  - model: pangu_rwrf
  - _self_
  - override hydra/job_logging: default # default/disabled/custom