hydra:
  run:  
    dir: outputs/${now:%Y-%m-%d}/${now:%H:%M:%S}
  job:
    chdir: False
  output_subdir: .hydra
  job_logging:
    root:
      level: DEBUG
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG

lightning:
  sampling_rate: 1
  batch_size: 8
  workers: 12
  limit_train_batches: null
  limit_val_batches: null

model:
  image_channels: 1
  hidden_dim: 32

defaults:
  - data: rwrf
  - lightning: diffusion_rwrf
  - model: diffusion_rwrf
  - _self_
  - override hydra/job_logging: default