hydra:
  run:  
    dir: outputs/${now:%Y-%m-%d}/${now:%H:%M:%S}
  job:
    chdir: False
  output_subdir: .hydra
  job_logging:
    root:
      level: DEBUG
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG

defaults:
  - data: rwrf_202409
  - lightning: diffusion_rwrf_202409
  - model: diffusion_rwrf_202409
  - _self_
  - override hydra/job_logging: default