# LightningDatamodule
input_len: 1
output_len: 1
split_config:
  ratios: [6, 2, 2]
  order_by_time: True
sampling_rate: 1
batch_size: 1
workers: 16
# LightningModule
regression_onnx_path: "./export/Pangu_model.onnx"
image_shape: [224, 224]
loss_factor: 1
optim_config:
  name: AdamW
  args:
    lr: 1e-4
warmup_epochs: 20
# lightning.Trainer
num_gpus: null
strategy: "ddp"
fast_dev_run: False
max_epochs: null
max_steps: null
min_steps: 1e5 # 100k
limit_train_batches: null
limit_val_batches: null
early_stop_patience: 10
log_image_every_n_steps: 5e3
log_every_n_steps: 5e2
resume_from_checkpoint: null
precision: "bf16-mixed"
