# LightningDatamodule
input_len: 1
output_len: 1
split_config:
  ratios: [6, 2, 2]
  order_by_time: True
sampling_rate: 2
batch_size: 1
workers: 32
# LightningModule
regression_onnx_path: "./export/Pangu_model.onnx"
image_shape: [224, 224]
crps_alpha: 1e3
optim_config:
  name: AdamW
  args:
    lr: 2e-4
    weight_decay: 3e-6
warmup_epochs: 10
# lightning.Trainer
num_gpus: null
strategy: "ddp"
fast_dev_run: False
max_epochs: null
min_steps: 1e5 # 100k
limit_train_batches: 650
limit_val_batches: 400
early_stop_patience: 5
log_image_every_n_steps: 5e3
log_every_n_steps: 500
