# LightningDatamodule
input_len: 1
output_len: 1
split_config:
  ratios: [6, 2, 2]
  order_by_time: True
sampling_rate: 3
batch_size: 4
workers: 16
# LightningModule
image_shape: [224, 224]
surface_alpha: 0.25
optim_config:
  name: AdamW
  args:
    lr: 2e-4
    weight_decay: 3e-6
lr_schedule:
  name: cosine
  args:
    warmup_steps: 1000
# lightning.Trainer
num_gpus: null
strategy: "auto"
fast_dev_run: False
max_epochs: -1
max_steps: null
min_steps: 5e4 # 50k
limit_train_batches: null
limit_val_batches: null
early_stop_patience: 10
log_image_every_n_steps: 5e3
log_every_n_steps: 50 # default 50
resume_from_checkpoint: null
precision: "bf16-mixed"